name: Auto Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          source_branch: master
          pr_title: "Merge master to main"
          pr_body: "Automatic pull request from master branch to main branch"
          github_token: ${{ secrets.GITHUB_TOKEN }}
